version: "3.8"
services:
  postgis:
    image: supabase/postgres:13.3.0
    container_name: ulala_postgis
    restart: always
    ports:
      - "5432:5432"
    environment:
#      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ulala123!@#
      POSTGRES_DB: mydb
    volumes:
      - ./local_pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d/ # 디렉토리 지정

# docker admin 로그인시 hostname 설정을 host.docker.internal 로 설정
  pgadmin:
    image: dpage/pgadmin4
    container_name: ulala_postgis_admin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ulala.the.great@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ulala123!@#
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: